### ISSUE TITLE
Error in adding Mass Start Event in RaceDB v3.0.87-20230729105401

### ISSUE THREAD

**Issue by ChainGangEvents** [esitarski/RaceDB#49]
Get the following error message when trying to add another Mass event:  'EventMassStart' instance needs to have a primary key value before this relationship can be used.

Environment:

Request Method: GET
Request URL: http://localhost:8000/RaceDB/Competitions/CompetitionDashboard/240/EventMassStartNew/240/

Django Version: 4.2
Python Version: 3.10.11
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_extensions',
 'crispy_forms',
 'crispy_bootstrap3',
 'core')
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Template error:
In template /RaceDB/core/templates/event_mass_start_form.html, error at line 24
   'EventMassStart' instance needs to have a primary key value before this relationship can be used.
   14 : 
   15 : {% block content %}
   16 : 
   17 : <h2 class="hidden-print">{{title}}</h2>
   18 : <h2><strong>{{instance.competition.name}}</strong>: {{instance.competition.date_range_year_str}}</h2>
   19 : <h2 class="visible-print"><strong>{{instance.name}}</strong>: {{instance.date_time|date_hhmm}}</h2>
   20 : <hr class="hidden-print"/>
   21 : {% crispy form %}
   22 : <hr/>
   23 : {% spaceless %}
   24 :  {% with wave_set=instance.wave_set.all %} 
   25 : 	{% if wave_set.exists %}
   26 : 		<h2 class="visible-print">{% trans "Waves" %}</h2>
   27 : 		<table class="table table-striped table-hover">
   28 : 		<thead>
   29 : 			<tr>
   30 : 				<th></th>
   31 : 				<th>{% trans "Wave" %}</th>
   32 : 				<th>{% trans "Start Offset" %}</th>
   33 : 				<th>{% trans "Categories" %}</th>
   34 : 				<th>{% trans "Rank Together" %}</th>

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/RaceDB/core/views_common.py", line 108, in wrap
    response = response or decorated_func( request, *args, **kwargs )
  File "/RaceDB/core/WriteLog.py", line 90, in new_f
    return f( *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/RaceDB/core/views.py", line 2150, in EventMassStartNew
    return render( request, 'event_mass_start_form.html', locals() )
  File "/usr/local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 414, in render
    return strip_spaces_between_tags(self.nodelist.render(context).strip())
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 539, in render
    values = {key: val.resolve(context) for key, val in self.extra_context.items()}
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 539, in <dictcomp>
    values = {key: val.resolve(context) for key, val in self.extra_context.items()}
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 715, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 914, in _resolve_lookup
    current = current()
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 164, in all
    return self.get_queryset()
  File "/usr/local/lib/python3.10/site-packages/django/db/models/fields/related_descriptors.py", line 718, in get_queryset
    raise ValueError(

Exception Type: ValueError at /RaceDB/Competitions/CompetitionDashboard/240/EventMassStartNew/240/
Exception Value: 'EventMassStart' instance needs to have a primary key value before this relationship can be used.

**Comment by esitarski** [comment]
Fixed in latest version.

**Comment by ChainGangEvents** [comment]
Thank you @esitarski the latest version works perfect. Closing this issue.
